name: CI/CD for Helm App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Deploy Backend via Helm
      run: |
        helm upgrade --install backend ./k8s-helm/backend-chart \
          --namespace default --create-namespace \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/backend \
          --set image.tag=latest

    - name: Deploy Frontend via Helm
      run: |
        helm upgrade --install frontend ./k8s-helm/frontend-chart \
          --namespace default --create-namespace \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/frontend \
          --set image.tag=latest
